//! `nx doc`: static HTML from `///` comments and the type system, including
//! inferred effect signatures (spec 17.4).

use crate::ast::*;
use crate::check::Program;
use std::fmt::Write;

fn esc(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;")
}

fn type_str(t: &TypeExpr) -> String {
    match t {
        TypeExpr::Named { path, args, .. } => {
            let n = path.join(".");
            if args.is_empty() {
                n
            } else {
                format!("{}({})", n, args.iter().map(type_str).collect::<Vec<_>>().join(", "))
            }
        }
        TypeExpr::Array { elem, .. } => format!("[N]{}", type_str(elem)),
        TypeExpr::Slice { mutable, elem, .. } => format!("[]{}{}", if *mutable { "mut " } else { "" }, type_str(elem)),
        TypeExpr::Ptr { mutable, elem, .. } => format!("*{}{}", if *mutable { "mut " } else { "" }, type_str(elem)),
        TypeExpr::Optional { elem, .. } => format!("?{}", type_str(elem)),
        TypeExpr::ErrorUnion { set, elem, .. } => format!("{}!{}", set.as_ref().map(|s| type_str(s)).unwrap_or_default(), type_str(elem)),
        TypeExpr::Fn { params, ret, .. } => format!("fn({}) -> {}", params.iter().map(type_str).collect::<Vec<_>>().join(", "), type_str(ret)),
        TypeExpr::Tuple { elems, .. } => format!("({})", elems.iter().map(type_str).collect::<Vec<_>>().join(", ")),
        TypeExpr::Weak { elem, .. } => format!("weak {}", type_str(elem)),
        TypeExpr::Dyn { trait_name, .. } => format!("dyn {}", trait_name),
        TypeExpr::Infer { .. } => "_".into(),
    }
}

fn fn_sig(f: &FnDecl) -> String {
    let params: Vec<String> = f.params.iter().map(|p| format!("{}{}: {}", if p.comptime { "comptime " } else { "" }, p.name, type_str(&p.ty))).collect();
    let ret = f.ret.as_ref().map(|r| format!(" -> {}", type_str(r))).unwrap_or_default();
    format!("{}fn {}({}){}", if f.attrs.is_pub { "pub " } else { "" }, f.name, params.join(", "), ret)
}

fn docs_html(doc: &[String]) -> String {
    if doc.is_empty() {
        return String::new();
    }
    format!("<p class=\"doc\">{}</p>", esc(&doc.join(" ")))
}

pub fn generate(title: &str, modules: &[Module], names: &[String], prog: &Program) -> String {
    let mut h = String::new();
    let _ = write!(
        h,
        "<!doctype html><html><head><meta charset=\"utf-8\"><title>{t}</title><style>
body{{font-family:system-ui,sans-serif;max-width:60rem;margin:2rem auto;padding:0 1rem;line-height:1.5;color:#222}}
code,pre{{font-family:ui-monospace,Consolas,monospace;background:#f4f4f6;border-radius:4px}}
pre{{padding:.6rem .8rem;overflow:auto}} code{{padding:0 .25rem}}
h2{{border-bottom:1px solid #ddd;padding-bottom:.2rem;margin-top:2rem}}
.item{{margin:1.2rem 0}} .eff{{color:#7a3e00;font-size:.9em}} .doc{{margin:.3rem 0 0 1rem}}
.fields{{margin:.3rem 0 0 1rem;color:#444}} nav a{{margin-right:1rem}}
</style></head><body><h1>{t}</h1><p>Generated by <code>nx doc</code>. Effects are inferred by the compiler, not written by hand.</p>",
        t = esc(title)
    );
    for (m, name) in modules.iter().zip(names.iter()) {
        let _ = write!(h, "<h2>module {}</h2>", esc(name));
        for item in &m.items {
            match item {
                Item::Fn(f) if f.attrs.is_pub || f.export.is_some() => {
                    let eff = prog.funcs.iter().find(|tf| tf.name == f.name && tf.def.is_some() && tf.targs.is_empty()).map(|tf| tf.effects);
                    let eff_s = match eff {
                        Some(e) if e.is_empty() => "pure (no effects)".to_string(),
                        Some(e) => format!("effects: {}", e.render()),
                        None => "effects: (generic; inferred per instantiation)".to_string(),
                    };
                    let _ = write!(
                        h,
                        "<div class=\"item\" id=\"fn-{n}\"><pre>{sig}{exp}</pre><div class=\"eff\">{eff}</div>{doc}</div>",
                        n = esc(&f.name),
                        sig = esc(&fn_sig(f)),
                        exp = f.export.as_ref().map(|e| format!(" export({})", e)).unwrap_or_default(),
                        eff = esc(&eff_s),
                        doc = docs_html(&f.attrs.doc)
                    );
                }
                Item::Struct(s) if s.attrs.is_pub => {
                    let kw = match s.kind {
                        StructKind::Struct => "struct",
                        StructKind::Record => "record",
                        StructKind::RefClass => "ref class",
                    };
                    let mut fields = String::new();
                    for f in &s.fields {
                        let c = f.constraint.as_ref().map(|_| " (constrained)").unwrap_or("");
                        let _ = write!(fields, "<div><code>{}: {}</code>{}{}</div>", esc(&f.name), esc(&type_str(&f.ty)), c, docs_html(&f.doc));
                    }
                    let _ = write!(
                        h,
                        "<div class=\"item\"><pre>{} {}{}</pre>{}<div class=\"fields\">{}</div></div>",
                        kw,
                        esc(&s.name),
                        if s.type_params.is_empty() { String::new() } else { format!("({})", s.type_params.join(", ")) },
                        docs_html(&s.attrs.doc),
                        fields
                    );
                }
                Item::Enum(e) if e.attrs.is_pub => {
                    let vs: Vec<String> = e.variants.iter().map(|v| esc(&v.name)).collect();
                    let _ = write!(h, "<div class=\"item\"><pre>enum {}</pre>{}<div class=\"fields\">variants: {}</div></div>", esc(&e.name), docs_html(&e.attrs.doc), vs.join(", "));
                }
                Item::Trait(t) if t.attrs.is_pub => {
                    let ms: Vec<String> = t.methods.iter().map(|m| esc(&fn_sig(m))).collect();
                    let _ = write!(h, "<div class=\"item\"><pre>trait {}</pre>{}<div class=\"fields\"><pre>{}</pre></div></div>", esc(&t.name), docs_html(&t.attrs.doc), ms.join("\n"));
                }
                Item::Const(c) if c.attrs.is_pub => {
                    let _ = write!(
                        h,
                        "<div class=\"item\"><pre>const {}{}</pre>{}</div>",
                        esc(&c.name),
                        c.ty.as_ref().map(|t| format!(": {}", esc(&type_str(t)))).unwrap_or_default(),
                        docs_html(&c.attrs.doc)
                    );
                }
                Item::ErrorSet(e) if e.attrs.is_pub => {
                    let _ = write!(h, "<div class=\"item\"><pre>error {} {{ {} }}</pre></div>", esc(&e.name), e.names.join(", "));
                }
                Item::TypeAlias(a) if a.attrs.is_pub => {
                    let _ = write!(h, "<div class=\"item\"><pre>type {} = {}{}</pre></div>", esc(&a.name), if a.distinct { "distinct " } else { "" }, esc(&type_str(&a.ty)));
                }
                _ => {}
            }
        }
    }
    h.push_str("</body></html>\n");
    h
}
