//! `artifact node`: an npm package over the shared library.
//!
//! The package is plain JavaScript calling the library through `koffi`
//! (a prebuilt FFI package on npm), so it needs no build step, no
//! node-gyp and no N-API headers on the user's machine. Errors from Nexium
//! code arrive as `NexiumError`; a panic inside the library is caught at
//! the export boundary and becomes `NexiumPanic`. A `.d.ts` gives every
//! export its types.

use crate::cgen::exports::{ExportInfo, ParamKind, ScalarKind};
use crate::types::IntTy;
use std::fmt::Write;

fn koffi_type(k: &ScalarKind) -> &'static str {
    match k {
        ScalarKind::Int(IntTy::I8) => "int8",
        ScalarKind::Int(IntTy::I16) => "int16",
        ScalarKind::Int(IntTy::I32) => "int32",
        ScalarKind::Int(IntTy::I64) => "int64",
        ScalarKind::Int(IntTy::U8) => "uint8",
        ScalarKind::Int(IntTy::U16) => "uint16",
        ScalarKind::Int(IntTy::U32) => "uint32",
        ScalarKind::Int(IntTy::U64) => "uint64",
        ScalarKind::Int(IntTy::Isize) => "intptr",
        ScalarKind::Int(IntTy::Usize) => "size_t",
        ScalarKind::Int(_) => "int64",
        ScalarKind::F32 => "float32",
        ScalarKind::F64 => "float64",
        ScalarKind::Bool => "bool",
        ScalarKind::Char => "uint32",
    }
}

/// The typed array a slice of this element is exchanged through.
fn typed_array(k: &ScalarKind) -> &'static str {
    match k {
        ScalarKind::Int(IntTy::I8) => "Int8Array",
        ScalarKind::Int(IntTy::U8) | ScalarKind::Bool => "Uint8Array",
        ScalarKind::Int(IntTy::I16) => "Int16Array",
        ScalarKind::Int(IntTy::U16) => "Uint16Array",
        ScalarKind::Int(IntTy::I32) => "Int32Array",
        ScalarKind::Int(IntTy::U32) | ScalarKind::Char => "Uint32Array",
        ScalarKind::Int(IntTy::I64) | ScalarKind::Int(IntTy::Isize) => "BigInt64Array",
        ScalarKind::Int(IntTy::U64) | ScalarKind::Int(IntTy::Usize) => "BigUint64Array",
        ScalarKind::Int(_) => "BigInt64Array",
        ScalarKind::F32 => "Float32Array",
        ScalarKind::F64 => "Float64Array",
    }
}

fn ts_type(k: &ScalarKind) -> &'static str {
    match k {
        ScalarKind::Int(IntTy::I64) | ScalarKind::Int(IntTy::U64) | ScalarKind::Int(IntTy::Isize) | ScalarKind::Int(IntTy::Usize) | ScalarKind::Int(IntTy::I128) | ScalarKind::Int(IntTy::U128) => {
            "bigint"
        }
        ScalarKind::Int(_) | ScalarKind::Char | ScalarKind::F32 | ScalarKind::F64 => "number",
        ScalarKind::Bool => "boolean",
    }
}

fn struct_name(c_name: &str) -> String {
    c_name.trim_start_matches("nx_").to_string()
}

/// The `index.js` of the package.
pub fn module(lib: &str, version: &str, infos: &[ExportInfo], libfile: &str) -> String {
    let mut js = String::new();
    let _ = writeln!(
        js,
        "// {lib} {version} - generated by nx from a Nexium source tree.\n//\n// Every function calls into the native library through koffi. Errors raised\n// by the Nexium code arrive as NexiumError; a panic inside the native code is\n// caught at the boundary and raised as NexiumPanic.\n'use strict';\nconst path = require('path');\nconst koffi = require('koffi');\n\nconst lib = koffi.load(path.join(__dirname, {libfile:?}));\nconst errorName = lib.func('{lib}_error_name', 'str', ['int32']);\nconst lastPanic = lib.func('{lib}_last_panic', 'str', []);\n\nclass NexiumError extends Error {{\n  constructor(code) {{\n    const name = errorName(code);\n    super(name);\n    this.name = 'NexiumError';\n    this.code = code;\n    this.errorName = name;\n  }}\n}}\n\nclass NexiumPanic extends NexiumError {{\n  constructor(code) {{\n    super(code);\n    this.name = 'NexiumPanic';\n    this.message = lastPanic();\n  }}\n}}\n\nfunction raise(code) {{\n  if (errorName(code) === 'Panic') throw new NexiumPanic(code);\n  throw new NexiumError(code);\n}}\n\n// a slice argument: a typed array is passed as is, anything iterable is copied\nfunction buf(value, Ctor) {{\n  if (value instanceof Ctor) return value;\n  if (typeof value === 'string') return Buffer.from(value, 'utf8');\n  if (Buffer.isBuffer(value) && Ctor === Uint8Array) return value;\n  return Ctor.from(value);\n}}\n",
        lib = lib,
        version = version,
        libfile = libfile
    );
    // structs
    let mut seen: Vec<String> = Vec::new();
    for info in infos {
        let mut kinds: Vec<&ParamKind> = info.params.iter().map(|p| &p.kind).collect();
        if let Some((_, k)) = &info.ret {
            kinds.push(k);
        }
        for k in kinds {
            if let ParamKind::Struct { c_name, fields } = k {
                if seen.contains(c_name) {
                    continue;
                }
                seen.push(c_name.clone());
                let name = struct_name(c_name);
                let members: Vec<String> = fields.iter().map(|(n, sk, _)| format!("{}: '{}'", n, koffi_type(sk))).collect();
                let _ = writeln!(js, "const {name}_t = koffi.struct('{name}', {{ {members} }});", name = name, members = members.join(", "));
            }
        }
    }
    let _ = writeln!(js);
    // bindings
    for info in infos {
        let mut ctypes: Vec<String> = Vec::new();
        let mut params: Vec<String> = Vec::new();
        let mut conv: Vec<String> = Vec::new();
        let mut call: Vec<String> = Vec::new();
        for p in &info.params {
            match &p.kind {
                ParamKind::Scalar(s) => {
                    ctypes.push(format!("'{}'", koffi_type(s)));
                    params.push(p.name.clone());
                    call.push(p.name.clone());
                }
                ParamKind::Slice { elem, mutable, .. } => {
                    ctypes.push(format!("'{}{} *'", if *mutable { "_Inout_ " } else { "" }, koffi_type(elem)));
                    ctypes.push("'size_t'".into());
                    params.push(p.name.clone());
                    conv.push(format!("  const _{n} = buf({n}, {ta});", n = p.name, ta = typed_array(elem)));
                    call.push(format!("_{}", p.name));
                    call.push(format!("_{}.length", p.name));
                }
                ParamKind::Struct { c_name, .. } => {
                    ctypes.push(format!("{}_t", struct_name(c_name)));
                    params.push(p.name.clone());
                    call.push(p.name.clone());
                }
            }
        }
        let ret = info.ret.as_ref().map(|(_, k)| match k {
            ParamKind::Scalar(s) => koffi_type(s).to_string(),
            ParamKind::Struct { c_name, .. } => format!("{}_t", struct_name(c_name)),
            _ => "void".into(),
        });
        let effects = if info.effects.is_empty() { "none".to_string() } else { info.effects.clone() };
        if info.status {
            let mut all = ctypes.clone();
            if let Some(r) = &ret {
                all.push(format!("'_Out_ {} *'", r.trim_end_matches("_t")));
            }
            let _ = writeln!(js, "const _{name} = lib.func('{name}', 'int32', [{types}]);", name = info.name, types = all.join(", "));
            let _ = writeln!(js, "/** effects: {} */", effects);
            let _ = writeln!(js, "function {}({}) {{", info.name, params.join(", "));
            for c in &conv {
                let _ = writeln!(js, "{}", c);
            }
            match &ret {
                Some(r) => {
                    let mut c2 = call.clone();
                    c2.push("_out".into());
                    let _ = writeln!(
                        js,
                        "  const _out = [{}];\n  const code = _{}({});\n  if (code !== 0) raise(code);\n  return _out[0];",
                        if r.ends_with("_t") { "{}".to_string() } else { "0".to_string() },
                        info.name,
                        c2.join(", ")
                    );
                }
                None => {
                    let _ = writeln!(js, "  const code = _{}({});\n  if (code !== 0) raise(code);", info.name, call.join(", "));
                }
            }
            let _ = writeln!(js, "}}\n");
        } else {
            let rt = ret.clone().map(|r| if r.ends_with("_t") { r } else { format!("'{}'", r) }).unwrap_or_else(|| "'void'".into());
            let _ = writeln!(js, "const _{name} = lib.func('{name}', {rt}, [{types}]);", name = info.name, rt = rt, types = ctypes.join(", "));
            let _ = writeln!(js, "/** effects: {} (cannot panic) */", effects);
            let _ = writeln!(js, "function {}({}) {{", info.name, params.join(", "));
            for c in &conv {
                let _ = writeln!(js, "{}", c);
            }
            let _ = writeln!(js, "  return _{}({});\n}}\n", info.name, call.join(", "));
        }
    }
    let names: Vec<String> = infos.iter().map(|i| i.name.clone()).collect();
    let _ = writeln!(js, "module.exports = {{ NexiumError, NexiumPanic, {} }};", names.join(", "));
    js
}

/// The `index.d.ts` of the package.
pub fn typings(infos: &[ExportInfo]) -> String {
    let mut ts = String::from("// generated by nx\nexport class NexiumError extends Error {\n  code: number;\n  errorName: string;\n}\nexport class NexiumPanic extends NexiumError {}\n\n");
    let mut seen: Vec<String> = Vec::new();
    for info in infos {
        let mut kinds: Vec<&ParamKind> = info.params.iter().map(|p| &p.kind).collect();
        if let Some((_, k)) = &info.ret {
            kinds.push(k);
        }
        for k in kinds {
            if let ParamKind::Struct { c_name, fields } = k {
                if seen.contains(c_name) {
                    continue;
                }
                seen.push(c_name.clone());
                let _ = writeln!(ts, "export interface {} {{", struct_name(c_name));
                for (n, sk, _) in fields {
                    let _ = writeln!(ts, "  {}: {};", n, ts_type(sk));
                }
                let _ = writeln!(ts, "}}\n");
            }
        }
    }
    for info in infos {
        let params: Vec<String> = info
            .params
            .iter()
            .map(|p| match &p.kind {
                ParamKind::Scalar(s) => format!("{}: {}", p.name, ts_type(s)),
                ParamKind::Slice { elem, .. } => {
                    format!("{}: {} | ArrayLike<{}>{}", p.name, typed_array(elem), ts_type(elem), if matches!(elem, ScalarKind::Int(IntTy::U8)) { " | string" } else { "" })
                }
                ParamKind::Struct { c_name, .. } => format!("{}: {}", p.name, struct_name(c_name)),
            })
            .collect();
        let ret = match &info.ret {
            Some((_, ParamKind::Scalar(s))) => ts_type(s).to_string(),
            Some((_, ParamKind::Struct { c_name, .. })) => struct_name(c_name),
            _ => "void".into(),
        };
        for d in &info.doc {
            let _ = writeln!(ts, "/** {} */", d);
        }
        let _ = writeln!(ts, "export function {}({}): {};", info.name, params.join(", "), ret);
    }
    ts
}

pub fn package_json(name: &str, version: &str, libfile: &str) -> String {
    format!(
        "{{\n  \"name\": {name:?},\n  \"version\": {version:?},\n  \"description\": \"{name} (built with Nexium)\",\n  \"main\": \"index.js\",\n  \"types\": \"index.d.ts\",\n  \"files\": [\"index.js\", \"index.d.ts\", {libfile:?}],\n  \"dependencies\": {{ \"koffi\": \"^2.9.0\" }},\n  \"engines\": {{ \"node\": \">=18\" }},\n  \"os\": [\"{os}\"],\n  \"cpu\": [\"{cpu}\"]\n}}\n",
        name = name,
        version = version,
        libfile = libfile,
        os = if cfg!(windows) { "win32" } else if cfg!(target_os = "macos") { "darwin" } else { "linux" },
        cpu = if cfg!(target_arch = "aarch64") { "arm64" } else { "x64" },
    )
}
