//! Artifact production: C headers, Python packages and wheels.

use crate::cgen::exports::{scalar_c, ExportInfo, ParamKind, ScalarKind};
use crate::types::IntTy;
use std::fmt::Write;
use std::path::Path;

pub fn c_header(lib: &str, infos: &[ExportInfo]) -> String {
    let guard = format!("{}_H", lib.to_uppercase().replace(|c: char| !c.is_ascii_alphanumeric(), "_"));
    let mut h = String::new();
    let _ = writeln!(h, "/* {} - generated by nx. Link the static library or load the shared one. */", lib);
    let _ = writeln!(h, "#ifndef {g}\n#define {g}\n#include <stdint.h>\n#include <stddef.h>\n#include <stdbool.h>\n#ifdef __cplusplus\nextern \"C\" {{\n#endif\n", g = guard);
    let _ = writeln!(h, "/* Status codes: 0 = ok. Any other value is an error code; {}_error_name() gives its name.\n   A Nexium panic inside a call is converted to the code named \"Panic\"; {}_last_panic() returns the message. */", lib, lib);
    let _ = writeln!(h, "const char* {}_error_name(int32_t code);\nconst char* {}_last_panic(void);\n", lib, lib);
    // struct definitions used by exports
    let mut seen = Vec::new();
    for info in infos {
        let mut kinds: Vec<&ParamKind> = info.params.iter().map(|p| &p.kind).collect();
        if let Some((_, k)) = &info.ret {
            kinds.push(k);
        }
        for k in kinds {
            if let ParamKind::Struct { c_name, fields } = k {
                if seen.contains(c_name) {
                    continue;
                }
                seen.push(c_name.clone());
                let _ = writeln!(h, "typedef struct {} {{", c_name);
                for (name, sk, cname) in fields {
                    let _ = writeln!(h, "  {} {}; /* {} */", scalar_c(sk), cname, name);
                }
                let _ = writeln!(h, "}} {};\n", c_name);
            }
        }
    }
    for info in infos {
        for d in &info.doc {
            let _ = writeln!(h, "/* {} */", d);
        }
        let mut params: Vec<String> = Vec::new();
        for p in &info.params {
            match &p.kind {
                ParamKind::Scalar(s) => params.push(format!("{} {}", scalar_c(s), p.name)),
                ParamKind::Slice { elem_c, mutable, .. } => {
                    params.push(format!("{}{}* {}", if *mutable { "" } else { "const " }, elem_c, p.name));
                    params.push(format!("size_t {}_len", p.name));
                }
                ParamKind::Struct { c_name, .. } => params.push(format!("{} {}", c_name, p.name)),
            }
        }
        if info.status {
            if let Some((c, _)) = &info.ret {
                params.push(format!("{}* out", c));
            }
            let _ = writeln!(
                h,
                "/* effects: {} */\nint32_t {}({});",
                if info.effects.is_empty() { "none" } else { &info.effects },
                info.name,
                if params.is_empty() { "void".into() } else { params.join(", ") }
            );
        } else {
            let r = info.ret.as_ref().map(|(c, _)| c.clone()).unwrap_or_else(|| "void".into());
            let _ = writeln!(
                h,
                "/* effects: {}; cannot panic, so it returns its value directly */\n{} {}({});",
                if info.effects.is_empty() { "none" } else { &info.effects },
                r,
                info.name,
                if params.is_empty() { "void".into() } else { params.join(", ") }
            );
        }
        h.push('\n');
    }
    let _ = writeln!(h, "#ifdef __cplusplus\n}}\n#endif\n#endif /* {} */", guard);
    h
}

fn py_ctype(k: &ScalarKind) -> &'static str {
    match k {
        ScalarKind::Int(IntTy::I8) => "ctypes.c_int8",
        ScalarKind::Int(IntTy::I16) => "ctypes.c_int16",
        ScalarKind::Int(IntTy::I32) => "ctypes.c_int32",
        ScalarKind::Int(IntTy::I64) => "ctypes.c_int64",
        ScalarKind::Int(IntTy::U8) => "ctypes.c_uint8",
        ScalarKind::Int(IntTy::U16) => "ctypes.c_uint16",
        ScalarKind::Int(IntTy::U32) => "ctypes.c_uint32",
        ScalarKind::Int(IntTy::U64) => "ctypes.c_uint64",
        ScalarKind::Int(IntTy::Isize) => "ctypes.c_ssize_t",
        ScalarKind::Int(IntTy::Usize) => "ctypes.c_size_t",
        ScalarKind::Int(_) => "ctypes.c_int64",
        ScalarKind::F32 => "ctypes.c_float",
        ScalarKind::F64 => "ctypes.c_double",
        ScalarKind::Bool => "ctypes.c_bool",
        ScalarKind::Char => "ctypes.c_uint32",
    }
}

fn py_hint(k: &ScalarKind) -> &'static str {
    match k {
        ScalarKind::Int(_) | ScalarKind::Char => "int",
        ScalarKind::F32 | ScalarKind::F64 => "float",
        ScalarKind::Bool => "bool",
    }
}

fn py_array_code(k: &ScalarKind) -> &'static str {
    match k {
        ScalarKind::Int(IntTy::I8) => "b",
        ScalarKind::Int(IntTy::U8) => "B",
        ScalarKind::Int(IntTy::I16) => "h",
        ScalarKind::Int(IntTy::U16) => "H",
        ScalarKind::Int(IntTy::I32) => "i",
        ScalarKind::Int(IntTy::U32) => "I",
        ScalarKind::Int(IntTy::I64) | ScalarKind::Int(IntTy::Isize) => "q",
        ScalarKind::Int(IntTy::U64) | ScalarKind::Int(IntTy::Usize) => "Q",
        ScalarKind::Int(_) => "q",
        ScalarKind::F32 => "f",
        ScalarKind::F64 => "d",
        ScalarKind::Bool => "B",
        ScalarKind::Char => "I",
    }
}

pub fn python_module(lib: &str, version: &str, infos: &[ExportInfo], libfile: &str) -> String {
    let mut py = String::new();
    let _ = writeln!(py, "\"\"\"{} - generated by nx from a Nexium source tree.\n\nEvery function here calls into the native library through ctypes. Errors\nraised by the Nexium code arrive as NexiumError; a panic inside the native\ncode is caught at the boundary and raised as NexiumPanic.\n\"\"\"\nimport ctypes\nimport os\nimport array\n\n__version__ = {:?}\n__all__ = [\"NexiumError\", \"NexiumPanic\"]\n\n_lib = ctypes.CDLL(os.path.join(os.path.dirname(os.path.abspath(__file__)), {:?}))\n_lib.{lib}_error_name.restype = ctypes.c_char_p\n_lib.{lib}_error_name.argtypes = [ctypes.c_int32]\n_lib.{lib}_last_panic.restype = ctypes.c_char_p\n_lib.{lib}_last_panic.argtypes = []\n\n\nclass NexiumError(Exception):\n    \"\"\"An error value returned by Nexium code.\"\"\"\n    def __init__(self, code):\n        self.code = code\n        self.name = _lib.{lib}_error_name(code).decode()\n        super().__init__(self.name)\n\n\nclass NexiumPanic(NexiumError):\n    \"\"\"A panic inside Nexium code, converted at the boundary.\"\"\"\n    def __init__(self, code):\n        super().__init__(code)\n        self.message = _lib.{lib}_last_panic().decode()\n        self.args = (self.message,)\n\n\ndef _raise(code):\n    if _lib.{lib}_error_name(code) == b\"Panic\":\n        raise NexiumPanic(code)\n    raise NexiumError(code)\n\n\ndef _buf(value, ctype, code, writable):\n    \"\"\"Turn a bytes/bytearray/array/list/memoryview into (pointer, length).\"\"\"\n    if isinstance(value, (bytes, bytearray, memoryview, array.array)):\n        mv = memoryview(value)\n        if mv.format != code and not (code == \"B\" and mv.format in (\"b\", \"c\")):\n            value = array.array(code, list(value))\n            mv = memoryview(value)\n        if writable and mv.readonly:\n            raise TypeError(\"a writable buffer (bytearray or array) is required\")\n        n = mv.nbytes // mv.itemsize\n        if writable:\n            arr = (ctype * n).from_buffer(value)\n        else:\n            arr = (ctype * n).from_buffer_copy(mv)\n        return arr, n\n    seq = list(value)\n    arr = (ctype * len(seq))(*seq)\n    return arr, len(seq)\n", lib, version, libfile, lib = lib);
    // struct classes
    let mut seen = Vec::new();
    for info in infos {
        let mut kinds: Vec<&ParamKind> = info.params.iter().map(|p| &p.kind).collect();
        if let Some((_, k)) = &info.ret {
            kinds.push(k);
        }
        for k in kinds {
            if let ParamKind::Struct { c_name, fields } = k {
                if seen.contains(c_name) {
                    continue;
                }
                seen.push(c_name.clone());
                let pyname = c_name.trim_start_matches("nx_").to_string();
                let _ = writeln!(py, "\n\nclass {}(ctypes.Structure):\n    _fields_ = [", pyname);
                for (name, sk, _) in fields {
                    let _ = writeln!(py, "        ({:?}, {}),", name, py_ctype(sk));
                }
                let _ = writeln!(
                    py,
                    "    ]\n\n    def __repr__(self):\n        return \"{}(\" + \", \".join(f\"{{n}}={{getattr(self, n)!r}}\" for n, _ in self._fields_) + \")\"\n\n__all__.append({:?})",
                    pyname, pyname
                );
            }
        }
    }
    for info in infos {
        let mut argtypes = Vec::new();
        let mut sig = Vec::new();
        let mut conv = Vec::new();
        let mut call = Vec::new();
        for p in &info.params {
            match &p.kind {
                ParamKind::Scalar(s) => {
                    argtypes.push(py_ctype(s).to_string());
                    sig.push(format!("{}: {}", p.name, py_hint(s)));
                    call.push(p.name.clone());
                }
                ParamKind::Slice { elem, mutable, .. } => {
                    argtypes.push(format!("ctypes.POINTER({})", py_ctype(elem)));
                    argtypes.push("ctypes.c_size_t".into());
                    sig.push(p.name.clone());
                    conv.push(format!("    _{n}, _{n}_len = _buf({n}, {ct}, {code:?}, {w})", n = p.name, ct = py_ctype(elem), code = py_array_code(elem), w = if *mutable { "True" } else { "False" }));
                    call.push(format!("_{}", p.name));
                    call.push(format!("_{}_len", p.name));
                }
                ParamKind::Struct { c_name, .. } => {
                    let pyname = c_name.trim_start_matches("nx_").to_string();
                    argtypes.push(pyname.clone());
                    sig.push(format!("{}: {}", p.name, pyname));
                    call.push(p.name.clone());
                }
            }
        }
        let ret_py = info.ret.as_ref().map(|(_, k)| match k {
            ParamKind::Scalar(s) => (py_ctype(s).to_string(), py_hint(s).to_string()),
            ParamKind::Struct { c_name, .. } => {
                let n = c_name.trim_start_matches("nx_").to_string();
                (n.clone(), n)
            }
            _ => ("None".into(), "None".into()),
        });
        let _ = writeln!(py, "\n");
        if info.status {
            let mut at = argtypes.clone();
            if let Some((ct, _)) = &ret_py {
                at.push(format!("ctypes.POINTER({})", ct));
            }
            let _ = writeln!(py, "_lib.{}.restype = ctypes.c_int32\n_lib.{}.argtypes = [{}]", info.name, info.name, at.join(", "));
            let _ = writeln!(py, "\n\ndef {}({}){}:", info.name, sig.join(", "), ret_py.as_ref().map(|(_, h)| format!(" -> {}", h)).unwrap_or_default());
            let _ = writeln!(py, "    \"\"\"effects: {}\"\"\"", if info.effects.is_empty() { "none" } else { &info.effects });
            for c in &conv {
                let _ = writeln!(py, "{}", c);
            }
            match &ret_py {
                Some((ct, _)) => {
                    let mut c2 = call.clone();
                    c2.push("ctypes.byref(_out)".into());
                    let _ = writeln!(
                        py,
                        "    _out = {}()\n    _code = _lib.{}({})\n    if _code != 0:\n        _raise(_code)\n    return _out.value if hasattr(_out, \"value\") else _out",
                        ct,
                        info.name,
                        c2.join(", ")
                    );
                }
                None => {
                    let _ = writeln!(py, "    _code = _lib.{}({})\n    if _code != 0:\n        _raise(_code)", info.name, call.join(", "));
                }
            }
        } else {
            let _ = writeln!(py, "_lib.{}.restype = {}\n_lib.{}.argtypes = [{}]", info.name, ret_py.as_ref().map(|(c, _)| c.clone()).unwrap_or_else(|| "None".into()), info.name, argtypes.join(", "));
            let _ = writeln!(py, "\n\ndef {}({}){}:", info.name, sig.join(", "), ret_py.as_ref().map(|(_, h)| format!(" -> {}", h)).unwrap_or_default());
            let _ = writeln!(py, "    \"\"\"effects: {} (cannot panic)\"\"\"", if info.effects.is_empty() { "none" } else { &info.effects });
            for c in &conv {
                let _ = writeln!(py, "{}", c);
            }
            let _ = writeln!(py, "    return _lib.{}({})", info.name, call.join(", "));
        }
        let _ = writeln!(py, "\n\n__all__.append({:?})", info.name);
    }
    py
}

fn rust_scalar(k: &ScalarKind) -> &'static str {
    match k {
        ScalarKind::Int(IntTy::I8) => "i8",
        ScalarKind::Int(IntTy::I16) => "i16",
        ScalarKind::Int(IntTy::I32) => "i32",
        ScalarKind::Int(IntTy::I64) => "i64",
        ScalarKind::Int(IntTy::U8) => "u8",
        ScalarKind::Int(IntTy::U16) => "u16",
        ScalarKind::Int(IntTy::U32) => "u32",
        ScalarKind::Int(IntTy::U64) => "u64",
        ScalarKind::Int(IntTy::Isize) => "isize",
        ScalarKind::Int(IntTy::Usize) => "usize",
        ScalarKind::Int(_) => "i64",
        ScalarKind::F32 => "f32",
        ScalarKind::F64 => "f64",
        ScalarKind::Bool => "bool",
        ScalarKind::Char => "u32",
    }
}

/// A Rust crate wrapping the static library: `Cargo.toml`, `build.rs`, and
/// `src/lib.rs` with `extern "C"` declarations plus safe wrappers.
pub fn rust_crate(lib: &str, version: &str, infos: &[ExportInfo], static_lib_file: &str) -> Vec<(String, String)> {
    let crate_name = lib.replace('-', "_");
    let cargo = format!(
        "[package]\nname = \"{}\"\nversion = \"{}\"\nedition = \"2021\"\nlinks = \"{}\"\nbuild = \"build.rs\"\ndescription = \"Rust bindings for the Nexium library {} (generated by nx ship)\"\n\n[lib]\npath = \"src/lib.rs\"\n",
        crate_name, version, lib, lib
    );
    let build = format!(
        "fn main() {{\n    let dir = std::path::Path::new(env!(\"CARGO_MANIFEST_DIR\")).join(\"lib\");\n    println!(\"cargo:rustc-link-search=native={{}}\", dir.display());\n    println!(\"cargo:rustc-link-lib=static={}\");\n    println!(\"cargo:rerun-if-changed=lib/{}\");\n}}\n",
        lib, static_lib_file
    );
    let mut rs = String::new();
    let _ = writeln!(rs, "//! Bindings for the Nexium library `{}`, generated by `nx ship`.\n//!\n//! Every exported function is wrapped: slices are passed as pointer and length,\n//! status-returning exports become `Result<T, NexiumError>`, and a panic inside\n//! Nexium code is reported as `NexiumError::Panic` rather than aborting.\n", lib);
    let _ = writeln!(rs, "use std::ffi::CStr;\nuse std::os::raw::c_char;\n\n#[derive(Debug, Clone, PartialEq, Eq)]\npub enum NexiumError {{\n    /// an error value returned by the Nexium code, by name\n    Error {{ code: i32, name: String }},\n    /// a panic caught at the boundary\n    Panic {{ message: String }},\n}}\n\nimpl std::fmt::Display for NexiumError {{\n    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{\n        match self {{\n            NexiumError::Error {{ name, .. }} => write!(f, \"{{}}\", name),\n            NexiumError::Panic {{ message }} => write!(f, \"panic: {{}}\", message),\n        }}\n    }}\n}}\nimpl std::error::Error for NexiumError {{}}\n");
    // struct types
    let mut seen = Vec::new();
    for info in infos {
        let mut kinds: Vec<&ParamKind> = info.params.iter().map(|p| &p.kind).collect();
        if let Some((_, k)) = &info.ret {
            kinds.push(k);
        }
        for k in kinds {
            if let ParamKind::Struct { c_name, fields } = k {
                if seen.contains(c_name) {
                    continue;
                }
                seen.push(c_name.clone());
                let name = c_name.trim_start_matches("nx_");
                let _ = writeln!(rs, "#[repr(C)]\n#[derive(Debug, Clone, Copy, PartialEq)]\npub struct {} {{", name);
                for (fname, sk, _) in fields {
                    let _ = writeln!(rs, "    pub {}: {},", fname, rust_scalar(sk));
                }
                let _ = writeln!(rs, "}}\n");
            }
        }
    }
    // raw declarations
    let _ = writeln!(
        rs,
        "mod ffi {{\n    use super::*;\n    extern \"C\" {{\n        pub fn {lib}_error_name(code: i32) -> *const c_char;\n        pub fn {lib}_last_panic() -> *const c_char;",
        lib = lib
    );
    for info in infos {
        let mut ps = Vec::new();
        for p in &info.params {
            match &p.kind {
                ParamKind::Scalar(s) => ps.push(format!("{}: {}", p.name, rust_scalar(s))),
                ParamKind::Slice { elem, mutable, .. } => {
                    ps.push(format!("{}: *{} {}", p.name, if *mutable { "mut" } else { "const" }, rust_scalar(elem)));
                    ps.push(format!("{}_len: usize", p.name));
                }
                ParamKind::Struct { c_name, .. } => ps.push(format!("{}: {}", p.name, c_name.trim_start_matches("nx_"))),
            }
        }
        let ret_rs = info.ret.as_ref().map(|(_, k)| match k {
            ParamKind::Scalar(s) => rust_scalar(s).to_string(),
            ParamKind::Struct { c_name, .. } => c_name.trim_start_matches("nx_").to_string(),
            _ => "()".into(),
        });
        if info.status {
            if let Some(r) = &ret_rs {
                ps.push(format!("out: *mut {}", r));
            }
            let _ = writeln!(rs, "        pub fn {}({}) -> i32;", info.name, ps.join(", "));
        } else {
            let _ = writeln!(rs, "        pub fn {}({}){};", info.name, ps.join(", "), ret_rs.as_ref().map(|r| format!(" -> {}", r)).unwrap_or_default());
        }
    }
    let _ = writeln!(rs, "    }}\n}}\n\nfn error_for(code: i32) -> NexiumError {{\n    // SAFETY: the library returns pointers to static NUL-terminated strings\n    let name = unsafe {{ CStr::from_ptr(ffi::{lib}_error_name(code)) }}.to_string_lossy().into_owned();\n    if name == \"Panic\" {{\n        let message = unsafe {{ CStr::from_ptr(ffi::{lib}_last_panic()) }}.to_string_lossy().into_owned();\n        NexiumError::Panic {{ message }}\n    }} else {{\n        NexiumError::Error {{ code, name }}\n    }}\n}}\n", lib = lib);
    // safe wrappers
    for info in infos {
        let mut sig = Vec::new();
        let mut call = Vec::new();
        for p in &info.params {
            match &p.kind {
                ParamKind::Scalar(s) => {
                    sig.push(format!("{}: {}", p.name, rust_scalar(s)));
                    call.push(p.name.clone());
                }
                ParamKind::Slice { elem, mutable, .. } => {
                    sig.push(format!("{}: &{}[{}]", p.name, if *mutable { "mut " } else { "" }, rust_scalar(elem)));
                    call.push(format!("{}.{}()", p.name, if *mutable { "as_mut_ptr" } else { "as_ptr" }));
                    call.push(format!("{}.len()", p.name));
                }
                ParamKind::Struct { c_name, .. } => {
                    sig.push(format!("{}: {}", p.name, c_name.trim_start_matches("nx_")));
                    call.push(p.name.clone());
                }
            }
        }
        let ret_rs = info.ret.as_ref().map(|(_, k)| match k {
            ParamKind::Scalar(s) => rust_scalar(s).to_string(),
            ParamKind::Struct { c_name, .. } => c_name.trim_start_matches("nx_").to_string(),
            _ => "()".into(),
        });
        let _ = writeln!(rs, "/// effects: {}", if info.effects.is_empty() { "none" } else { &info.effects });
        if info.status {
            match &ret_rs {
                Some(r) => {
                    let mut c2 = call.clone();
                    c2.push("&mut out".into());
                    let _ = writeln!(rs, "pub fn {}({}) -> Result<{}, NexiumError> {{\n    let mut out: {} = unsafe {{ std::mem::zeroed() }};\n    let code = unsafe {{ ffi::{}({}) }};\n    if code == 0 {{ Ok(out) }} else {{ Err(error_for(code)) }}\n}}\n", info.name, sig.join(", "), r, r, info.name, c2.join(", "));
                }
                None => {
                    let _ = writeln!(
                        rs,
                        "pub fn {}({}) -> Result<(), NexiumError> {{\n    let code = unsafe {{ ffi::{}({}) }};\n    if code == 0 {{ Ok(()) }} else {{ Err(error_for(code)) }}\n}}\n",
                        info.name,
                        sig.join(", "),
                        info.name,
                        call.join(", ")
                    );
                }
            }
        } else {
            let _ = writeln!(
                rs,
                "pub fn {}({}){} {{\n    unsafe {{ ffi::{}({}) }}\n}}\n",
                info.name,
                sig.join(", "),
                ret_rs.as_ref().map(|r| format!(" -> {}", r)).unwrap_or_default(),
                info.name,
                call.join(", ")
            );
        }
    }
    vec![("Cargo.toml".into(), cargo), ("build.rs".into(), build), ("src/lib.rs".into(), rs)]
}

pub fn python_stub(infos: &[ExportInfo]) -> String {
    let mut s = String::from("import ctypes\nfrom typing import Sequence\n\nclass NexiumError(Exception):\n    code: int\n    name: str\n\nclass NexiumPanic(NexiumError):\n    message: str\n\n");
    let mut seen = Vec::new();
    for info in infos {
        let mut kinds: Vec<&ParamKind> = info.params.iter().map(|p| &p.kind).collect();
        if let Some((_, k)) = &info.ret {
            kinds.push(k);
        }
        for k in kinds {
            if let ParamKind::Struct { c_name, fields } = k {
                if seen.contains(c_name) {
                    continue;
                }
                seen.push(c_name.clone());
                let pyname = c_name.trim_start_matches("nx_");
                let _ = writeln!(s, "class {}(ctypes.Structure):", pyname);
                for (name, sk, _) in fields {
                    let _ = writeln!(s, "    {}: {}", name, py_hint(sk));
                }
                let _ = writeln!(s, "    def __init__(self, {}) -> None: ...\n", fields.iter().map(|(n, k, _)| format!("{}: {} = ...", n, py_hint(k))).collect::<Vec<_>>().join(", "));
            }
        }
    }
    for info in infos {
        let sig: Vec<String> = info
            .params
            .iter()
            .map(|p| match &p.kind {
                ParamKind::Scalar(k) => format!("{}: {}", p.name, py_hint(k)),
                ParamKind::Slice { elem, .. } => format!("{}: Sequence[{}] | bytes | bytearray", p.name, py_hint(elem)),
                ParamKind::Struct { c_name, .. } => format!("{}: {}", p.name, c_name.trim_start_matches("nx_")),
            })
            .collect();
        let ret = info
            .ret
            .as_ref()
            .map(|(_, k)| match k {
                ParamKind::Scalar(s) => py_hint(s).to_string(),
                ParamKind::Struct { c_name, .. } => c_name.trim_start_matches("nx_").to_string(),
                _ => "None".into(),
            })
            .unwrap_or_else(|| "None".into());
        let _ = writeln!(s, "def {}({}) -> {}: ...", info.name, sig.join(", "), ret);
    }
    s
}

// ----- wheel ---------------------------------------------------------------

pub fn platform_tag(target: &str) -> String {
    let t = target.to_ascii_lowercase();
    if t.contains("windows") {
        if t.contains("aarch64") {
            "win_arm64".into()
        } else {
            "win_amd64".into()
        }
    } else if t.contains("macos") || t.contains("darwin") {
        if t.contains("aarch64") {
            "macosx_11_0_arm64".into()
        } else {
            "macosx_10_13_x86_64".into()
        }
    } else if t.contains("linux") {
        if t.contains("aarch64") {
            "manylinux_2_17_aarch64".into()
        } else {
            "manylinux_2_17_x86_64".into()
        }
    } else {
        "any".into()
    }
}

fn crc32(data: &[u8]) -> u32 {
    let mut table = [0u32; 256];
    for i in 0..256u32 {
        let mut c = i;
        for _ in 0..8 {
            c = if c & 1 != 0 { 0xEDB88320 ^ (c >> 1) } else { c >> 1 };
        }
        table[i as usize] = c;
    }
    let mut crc = 0xFFFFFFFFu32;
    for &b in data {
        crc = table[((crc ^ b as u32) & 0xff) as usize] ^ (crc >> 8);
    }
    crc ^ 0xFFFFFFFF
}

/// Write a stored (uncompressed) zip archive.
pub fn write_zip(path: &Path, files: &[(String, Vec<u8>)]) -> std::io::Result<()> {
    let mut out: Vec<u8> = Vec::new();
    let mut central: Vec<u8> = Vec::new();
    for (name, data) in files {
        let offset = out.len() as u32;
        let crc = crc32(data);
        let nb = name.as_bytes();
        // local header
        out.extend_from_slice(&[0x50, 0x4b, 0x03, 0x04, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
        out.extend_from_slice(&crc.to_le_bytes());
        out.extend_from_slice(&(data.len() as u32).to_le_bytes());
        out.extend_from_slice(&(data.len() as u32).to_le_bytes());
        out.extend_from_slice(&(nb.len() as u16).to_le_bytes());
        out.extend_from_slice(&0u16.to_le_bytes());
        out.extend_from_slice(nb);
        out.extend_from_slice(data);
        // central directory
        central.extend_from_slice(&[0x50, 0x4b, 0x01, 0x02, 20, 3, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
        central.extend_from_slice(&crc.to_le_bytes());
        central.extend_from_slice(&(data.len() as u32).to_le_bytes());
        central.extend_from_slice(&(data.len() as u32).to_le_bytes());
        central.extend_from_slice(&(nb.len() as u16).to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&(0o100644u32 << 16).to_le_bytes());
        central.extend_from_slice(&offset.to_le_bytes());
        central.extend_from_slice(nb);
    }
    let cd_offset = out.len() as u32;
    let cd_size = central.len() as u32;
    out.extend_from_slice(&central);
    out.extend_from_slice(&[0x50, 0x4b, 0x05, 0x06, 0, 0, 0, 0]);
    out.extend_from_slice(&(files.len() as u16).to_le_bytes());
    out.extend_from_slice(&(files.len() as u16).to_le_bytes());
    out.extend_from_slice(&cd_size.to_le_bytes());
    out.extend_from_slice(&cd_offset.to_le_bytes());
    out.extend_from_slice(&0u16.to_le_bytes());
    std::fs::write(path, out)
}

pub fn build_wheel(out_dir: &Path, name: &str, version: &str, tag: &str, package_files: &[(String, Vec<u8>)], summary: &str) -> std::io::Result<std::path::PathBuf> {
    let dist = format!("{}-{}.dist-info", name, version);
    let mut files: Vec<(String, Vec<u8>)> = package_files.to_vec();
    let metadata = format!("Metadata-Version: 2.1\nName: {}\nVersion: {}\nSummary: {}\nRequires-Python: >=3.8\n", name, version, summary);
    let wheel = format!("Wheel-Version: 1.0\nGenerator: nx\nRoot-Is-Purelib: false\nTag: py3-none-{}\n", tag);
    files.push((format!("{}/METADATA", dist), metadata.into_bytes()));
    files.push((format!("{}/WHEEL", dist), wheel.into_bytes()));
    files.push((format!("{}/top_level.txt", dist), format!("{}\n", name).into_bytes()));
    let mut record = String::new();
    for (n, d) in &files {
        let _ = writeln!(record, "{},sha256=,{}", n, d.len());
    }
    let _ = writeln!(record, "{}/RECORD,,", dist);
    files.push((format!("{}/RECORD", dist), record.into_bytes()));
    let path = out_dir.join(format!("{}-{}-py3-none-{}.whl", name, version, tag));
    write_zip(&path, &files)?;
    Ok(path)
}
